#!/bin/sh

CHERI_OUTPUT="/zdata/cheri/output"
CHERIBSD_VERSION=$(awk '/^#define[[:space:]]+__CheriBSD_version/{print $3}' /usr/include/sys/param.h)

prog=$(basename "${0}")

#
# Use host binaries and libraries for native tools.
#
export PATH="${CHERI_OUTPUT}/morello-sdk/bin:${PATH}"
export LD_LIBRARY_PATH="/host/usr/local/lib:/host/usr/lib:/host/lib"
#
# Overwrite variables from usr/local/etc/poudriere.d/*-make.conf so that
# subprocesses don't execute the user mode for shell again and instead directly
# execute utilities.
#
if [ "${CHERIBSD_VERSION}" -le 20220314 ]; then
	TLS_FLAGS="-femulated-tls"
	VARARG_FLAGS=
elif [ "${CHERIBSD_VERSION}" -le 20220828 ]; then
	TLS_FLAGS=
	VARARG_FLAGS="-Xclang -morello-vararg=new"
else
	TLS_FLAGS=
	VARARG_FLAGS="-Xclang -morello-vararg=new -Xclang -morello-bounded-memargs=caller-only"
fi
HOST_CFLAGS="-target aarch64-unknown-freebsd14.0 -march=morello -mabi=purecap ${TLS_FLAGS} ${VARARG_FLAGS}"
export ADDR2LINE="${CHERI_OUTPUT}/morello-sdk/bin/addr2line"
export AR="${CHERI_OUTPUT}/morello-sdk/bin/ar"
export CC="${CHERI_OUTPUT}/morello-sdk/utils/cheribsd-morello-purecap-clang ${HOST_CFLAGS}"
export CPP="${CHERI_OUTPUT}/morello-sdk/utils/cheribsd-morello-purecap-clang-cpp ${HOST_CFLAGS}"
export CPPFILT="${CHERI_OUTPUT}/morello-sdk/bin/c++filt"
export CXX="${CHERI_OUTPUT}/morello-sdk/utils/cheribsd-morello-purecap-clang++ ${HOST_CFLAGS}"
export LD="${CHERI_OUTPUT}/morello-sdk/bin/ld"
export NM="${CHERI_OUTPUT}/morello-sdk/bin/nm"
export OBJCOPY="${CHERI_OUTPUT}/morello-sdk/bin/objcopy"
export OBJDUMP="${CHERI_OUTPUT}/morello-sdk/bin/objdump"
export RANLIB="${CHERI_OUTPUT}/morello-sdk/bin/ranlib"
export READELF="${CHERI_OUTPUT}/morello-sdk/bin/readelf"
export SIZE="${CHERI_OUTPUT}/morello-sdk/bin/size"
export STRINGS="${CHERI_OUTPUT}/morello-sdk/bin/strings"
export STRIP="${CHERI_OUTPUT}/morello-sdk/bin/strip"
export AS="${CC}"

case "${prog}" in
as)
	${AS} "${@}"
	;;
cc|clang)
	${CC} "${@}"
	;;
cpp|clang-cpp)
	${CPP} "${@}"
	;;
c++|clang++)
	${CXX} "${@}"
	;;
*)
	"${CHERI_OUTPUT}/morello-sdk/bin/${prog}" "${@}"
	;;
esac
