#!/bin/sh

CHERI_OUTPUT="/zdata/cheri/output"

prog=$(basename "${0}")

export LD_LIBRARY_PATH="/host/usr/local/lib:/host/usr/lib:/host/lib"

#
# Overwrite variables from usr/local/etc/poudriere.d/*-make.conf so that
# subprocesses don't execute the user mode for shell again and instead directly
# execute utilities.
#
export LD="${CHERI_OUTPUT}/morello-sdk/bin/ld"
HOST_CFLAGS="--sysroot=${CHERI_OUTPUT}/morello-sdk/sysroot-morello-purecap -fuse-ld=${LD} -target aarch64-unknown-freebsd14.0 -march=morello+c64 -mabi=purecap -femulated-tls"
export CC="${CHERI_OUTPUT}/morello-sdk/utils/cheribsd-morello-purecap-clang ${HOST_CFLAGS}"
export CPP="${CHERI_OUTPUT}/morello-sdk/utils/cheribsd-morello-purecap-clang++ ${HOST_CFLAGS}"
export CXX="${CPP}"
export NM=${CHERI_OUTPUT}/morello-sdk/bin/nm
export OBJDUMP=${CHERI_OUTPUT}/morello-sdk/bin/objdump
export STRINGS=${CHERI_OUTPUT}/morello-sdk/bin/strings

case "${prog}" in
clang)
	${CC} "${@}"
	;;
clang++)
	${CPP} "${@}"
	;;
*)
	"${CHERI_OUTPUT}/morello-sdk/bin/${prog}" "${@}"
	;;
esac
