#!/bin/sh

CHERI_OUTPUT="/zdata/cheri/output"

prog=$(basename "${0}")

#
# Use host binaries and libraries for native tools.
#
export PATH="${CHERI_OUTPUT}/sdk/bin:${PATH}"
export LD_LIBRARY_PATH="/host/usr/local/lib:/host/usr/lib:/host/lib"
#
# Overwrite variables from usr/local/etc/poudriere.d/*-make.conf so that
# subprocesses don't execute the user mode for shell again and instead directly
# execute utilities.
#
export ADDR2LINE="${CHERI_OUTPUT}/sdk/bin/addr2line"
export AR="${CHERI_OUTPUT}/sdk/bin/ar"
export CC="${CHERI_OUTPUT}/sdk/bin/clang"
export CPP="${CHERI_OUTPUT}/sdk/bin/clang-cpp"
export CPPFILT="${CHERI_OUTPUT}/sdk/bin/c++filt"
export CXX="${CHERI_OUTPUT}/sdk/bin/clang++"
export LD="${CHERI_OUTPUT}/sdk/bin/ld"
export NM="${CHERI_OUTPUT}/sdk/bin/nm"
export OBJCOPY="${CHERI_OUTPUT}/sdk/bin/objcopy"
export OBJDUMP="${CHERI_OUTPUT}/sdk/bin/objdump"
export RANLIB="${CHERI_OUTPUT}/sdk/bin/ranlib"
export READELF="${CHERI_OUTPUT}/sdk/bin/readelf"
export SIZE="${CHERI_OUTPUT}/sdk/bin/size"
export STRINGS="${CHERI_OUTPUT}/sdk/bin/strings"
export STRIP="${CHERI_OUTPUT}/sdk/bin/strip"
export AS="${CC}"

case "${prog}" in
as)
	${AS} "${@}"
	;;
cc|clang)
	${CC} "${@}"
	;;
cpp|clang-cpp)
	${CPP} "${@}"
	;;
c++|clang++)
	${CXX} "${@}"
	;;
*)
	"${CHERI_OUTPUT}/sdk/bin/${prog}" "${@}"
	;;
esac
